/**
 * Off-machine backup of the full repository history.
 *
 *   node scripts/backup.mjs
 *
 * Writes a git bundle — a single file containing every commit, branch and tag —
 * then copies it to whichever cloud-synced folders exist. Needs no remote, no
 * network and no credentials, so it works while the push to origin is blocked.
 *
 * To restore, on any machine:
 *
 *   git clone merc-dashboard-<date>-<sha>.bundle sarkis-dashboard
 *
 * That produces a working repository with the complete history.
 *
 * NOT included, because git does not track them:
 *   .env.local   — secrets. Everything in it except EMAIL_FROM is also stored
 *                  in Vercel, so it is recoverable; see docs/carry-forward.md.
 *   .vercel/     — regenerated by `vercel link`.
 *   AUDIT.md     — deliberately gitignored.
 */

import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'

const git = (...args) => execFileSync('git', args, { encoding: 'utf8' }).trim()

const home = os.homedir()
const primary = path.join(home, 'merc-backups')

// Anywhere that syncs off the machine. Missing folders are skipped silently.
const mirrors = [
  path.join(home, 'OneDrive', 'merc-backups'),
  path.join(home, 'Dropbox', 'merc-backups'),
]

const sha = git('rev-parse', '--short', 'HEAD')
const stamp = new Date().toISOString().slice(0, 10)
const name = `merc-dashboard-${stamp}-${sha}.bundle`

fs.mkdirSync(primary, { recursive: true })
const target = path.join(primary, name)

console.log(`\nHEAD ${sha} · ${git('log', '-1', '--format=%s')}\n`)

const dirty = git('status', '--porcelain')
if (dirty) {
  console.log('  ⚠ Uncommitted changes — these are NOT in the bundle:')
  for (const line of dirty.split('\n')) console.log(`      ${line}`)
  console.log()
}

git('bundle', 'create', target, '--all')
git('bundle', 'verify', target)

const size = (fs.statSync(target).size / 1024).toFixed(0)
console.log(`  created  ${target}  (${size} KB, verified)`)

let copies = 1
for (const dir of mirrors) {
  const parent = path.dirname(dir)
  if (!fs.existsSync(parent)) continue
  fs.mkdirSync(dir, { recursive: true })
  const dest = path.join(dir, name)
  fs.copyFileSync(target, dest)
  git('bundle', 'verify', dest)          // throws if the copy is corrupt
  console.log(`  copied   ${dest}  (verified)`)
  copies++
}

// Keep the five most recent bundles in each location.
for (const dir of [primary, ...mirrors].filter(d => fs.existsSync(d))) {
  const old = fs.readdirSync(dir)
    .filter(f => f.endsWith('.bundle'))
    .sort()
    .reverse()
    .slice(5)
  for (const f of old) {
    fs.unlinkSync(path.join(dir, f))
    console.log(`  pruned   ${path.join(dir, f)}`)
  }
}

console.log(`\n✅  ${copies} verified copies, ${copies - 1} of them off this machine.\n`)
console.log(`  Restore with:  git clone ${name} sarkis-dashboard\n`)
